#!/bin/bash
# ============================================================
# install.sh - Multi-Service Installer for Debian
# Services: Apache2, vsftpd, OpenSSH, WordPress (optional)
# Generated by Generate-SetupScript.ps1
# ============================================================

# ─── Color Definitions ───────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# ─── Trap: Reset terminal on exit/interrupt ───────────────────
trap 'tput sgr0; echo ""' EXIT INT TERM

# ─── Logging Helper ──────────────────────────────────────────
log_info()    { echo -e "${GREEN}[INFO]${NC}  $1"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC}  $1"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $1"; }
log_section() { echo -e "\n${CYAN}${BOLD}══════════════════════════════════════${NC}"; echo -e "${CYAN}${BOLD}  $1${NC}"; echo -e "${CYAN}${BOLD}══════════════════════════════════════${NC}\n"; }

# ─── Root Check ──────────────────────────────────────────────
get_port_80_listener() {
    ss -tulpn 2>/dev/null | awk '/:80[[:space:]]/ && /LISTEN/ {print; exit}'
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "Script ini harus dijalankan sebagai root. Gunakan: sudo bash install.sh"
        exit 1
    fi
}

# ─── Banner ──────────────────────────────────────────────────
show_banner() {
    echo -e "${BLUE}${BOLD}"
    cat << "EOF"
 ████████╗███████╗ ██████╗██╗  ██╗ ██████╗ ██████╗ ██████╗ ██████╗ 
 ╚══██╔══╝██╔════╝██╔════╝██║  ██║██╔════╝██╔═══██╗██╔══██╗██╔══██╗
    ██║   █████╗  ██║     ███████║██║     ██║   ██║██████╔╝██████╔╝
    ██║   ██╔══╝  ██║     ██╔══██║██║     ██║   ██║██╔══██╗██╔═══╝ 
    ██║   ███████╗╚██████╗██║  ██║╚██████╗╚██████╔╝██║  ██║██║ 
    ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚═╝ 
EOF
    echo -e "${NC}"
    echo -e "${CYAN}${BOLD}  ┌─────────────────────────────────────────────────────┐${NC}"
    echo -e "${CYAN}${BOLD}  │   Multi-Service Installer | Apache2 + vsftpd + OpenSSH │${NC}"
    echo -e "${CYAN}${BOLD}  │              Target OS: Debian Latest                  │${NC}"
    echo -e "${CYAN}${BOLD}  └─────────────────────────────────────────────────────┘${NC}"
    echo ""
}

# ─── Menu ────────────────────────────────────────────────────
show_menu() {
    echo -e "${BOLD}${YELLOW}  ╔══════════════════════════════════╗${NC}"
    echo -e "${BOLD}${YELLOW}  ║         MENU INSTALASI           ║${NC}"
    echo -e "${BOLD}${YELLOW}  ╠══════════════════════════════════╣${NC}"
    echo -e "${BOLD}${YELLOW}  ║${NC}  1. Install Semua Service         ${BOLD}${YELLOW}║${NC}"
    echo -e "${BOLD}${YELLOW}  ║${NC}  2. Install Apache2 (Web Server)  ${BOLD}${YELLOW}║${NC}"
    echo -e "${BOLD}${YELLOW}  ║${NC}  3. Install FTP (vsftpd)          ${BOLD}${YELLOW}║${NC}"
    echo -e "${BOLD}${YELLOW}  ║${NC}  4. Install SSH (Secure Server)   ${BOLD}${YELLOW}║${NC}"
    echo -e "${BOLD}${YELLOW}  ║${NC}  5. Install WordPress             ${BOLD}${YELLOW}║${NC}"
    echo -e "${BOLD}${YELLOW}  ║${NC}  6. Exit                          ${BOLD}${YELLOW}║${NC}"
    echo -e "${BOLD}${YELLOW}  ╚══════════════════════════════════╝${NC}"
    echo ""
}

prompt_menu_choice() {
    while true; do
        printf "\033[0;36mPilih opsi [1-6]: \033[0m"
        if ! IFS= read -r CHOICE < /dev/tty; then
            echo ""
            log_error "Gagal membaca input dari terminal."
            return 1
        fi

        case "$CHOICE" in
            [1-6])
                return 0
                ;;
            *)
                log_error "Pilihan tidak valid. Masukkan angka 1-6."
                ;;
        esac
    done
}

# ─── System Update ───────────────────────────────────────────
system_update() {
    log_section "System Update & Upgrade"
    log_info "Memperbarui daftar paket..."
    apt update -y
    log_info "Mengupgrade paket yang sudah terinstall..."
    apt upgrade -y
    log_info "Membersihkan cache paket..."
    apt autoremove -y
    apt clean
    log_info "System update selesai."
}

# ─── Apache2 Installation ────────────────────────────────────
install_apache() {
    log_section "Instalasi Apache2 Web Server"

    log_info "Menginstall apache2..."
    apt install -y apache2

    log_info "Membuat halaman index.html profil TechCorp..."
    cat > /var/www/html/index.html << 'HTMLEOF'
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TechCorp - Solusi Teknologi Terdepan</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #0a0a1a; color: #e0e0e0; }
        header { background: linear-gradient(135deg, #1a1a3e, #0d47a1); padding: 60px 20px; text-align: center; border-bottom: 3px solid #2196F3; }
        header h1 { font-size: 3.5em; color: #2196F3; letter-spacing: 4px; text-shadow: 0 0 20px rgba(33,150,243,0.5); }
        header p { font-size: 1.2em; color: #90CAF9; margin-top: 10px; }
        nav { background: #0d1b2a; padding: 15px; text-align: center; position: sticky; top: 0; z-index: 100; }
        nav a { color: #2196F3; text-decoration: none; margin: 0 20px; font-weight: bold; font-size: 1em; transition: color 0.3s; }
        nav a:hover { color: #64B5F6; }
        .container { max-width: 1100px; margin: 0 auto; padding: 40px 20px; }
        .section { margin-bottom: 60px; }
        .section h2 { font-size: 2em; color: #2196F3; border-left: 5px solid #2196F3; padding-left: 15px; margin-bottom: 20px; }
        .about-text { font-size: 1.1em; line-height: 1.8; color: #b0bec5; }
        .services-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 25px; margin-top: 20px; }
        .service-card { background: #0d1b2a; border: 1px solid #1565C0; border-radius: 12px; padding: 30px; text-align: center; transition: transform 0.3s, box-shadow 0.3s; }
        .service-card:hover { transform: translateY(-8px); box-shadow: 0 10px 30px rgba(33,150,243,0.3); }
        .service-card .icon { font-size: 3em; margin-bottom: 15px; }
        .service-card h3 { color: #2196F3; font-size: 1.3em; margin-bottom: 10px; }
        .service-card p { color: #90A4AE; line-height: 1.6; }
        .contact-info { background: #0d1b2a; border-radius: 12px; padding: 30px; border: 1px solid #1565C0; }
        .contact-info p { margin: 12px 0; font-size: 1.05em; color: #b0bec5; }
        .contact-info span { color: #2196F3; font-weight: bold; }
        footer { background: #050510; text-align: center; padding: 25px; color: #546E7A; border-top: 1px solid #1565C0; }
        footer span { color: #2196F3; }
    </style>
</head>
<body>
    <header>
        <h1>⚡ TECHCORP</h1>
        <p>Solusi Teknologi Terdepan untuk Bisnis Modern</p>
    </header>
    <nav>
        <a href="#about">Tentang Kami</a>
        <a href="#services">Layanan</a>
        <a href="#contact">Kontak</a>
    </nav>
    <div class="container">
        <div class="section" id="about">
            <h2>Tentang Kami</h2>
            <p class="about-text">
                <strong style="color:#2196F3">TechCorp</strong> adalah perusahaan teknologi terkemuka yang berdedikasi
                untuk memberikan solusi digital inovatif kepada klien kami. Dengan pengalaman lebih dari 10 tahun,
                kami telah membantu ratusan bisnis bertransformasi secara digital, meningkatkan efisiensi operasional,
                dan memperkuat keamanan infrastruktur IT mereka. Tim kami terdiri dari para profesional berpengalaman
                yang siap memberikan layanan terbaik 24/7.
            </p>
        </div>
        <div class="section" id="services">
            <h2>Layanan Kami</h2>
            <div class="services-grid">
                <div class="service-card">
                    <div class="icon">🌐</div>
                    <h3>Web Development</h3>
                    <p>Pengembangan website dan aplikasi web modern, responsif, dan berperforma tinggi menggunakan teknologi terkini.</p>
                </div>
                <div class="service-card">
                    <div class="icon">🔒</div>
                    <h3>Cybersecurity</h3>
                    <p>Perlindungan menyeluruh terhadap ancaman siber, audit keamanan, penetration testing, dan incident response.</p>
                </div>
            </div>
        </div>
        <div class="section" id="contact">
            <h2>Kontak</h2>
            <div class="contact-info">
                <p>🏢 <span>Perusahaan:</span> TechCorp Indonesia</p>
                <p>📍 <span>Alamat:</span> Jl. Teknologi No. 1, Jakarta Selatan, DKI Jakarta 12345</p>
                <p>📧 <span>Email:</span> info@techcorp.id</p>
                <p>📞 <span>Telepon:</span> +62 21 1234 5678</p>
                <p>🌐 <span>Website:</span> www.techcorp.id</p>
                <p>⏰ <span>Jam Operasional:</span> Senin - Jumat, 08:00 - 17:00 WIB</p>
            </div>
        </div>
    </div>
    <footer>
        <p>&copy; 2024 <span>TechCorp Indonesia</span>. All Rights Reserved.</p>
    </footer>
</body>
</html>
HTMLEOF

    log_info "Mengatur permission file web..."
    chown -R www-data:www-data /var/www/html
    chmod -R 755 /var/www/html

    log_info "Mengatur ServerName Apache2..."
    SERVER_NAME="$(hostname -f 2>/dev/null || hostname)"
    if [[ -z "$SERVER_NAME" || "$SERVER_NAME" == "(none)" ]]; then
        SERVER_NAME="localhost"
    fi
    cat > /etc/apache2/conf-available/servername.conf << APACHECONF
ServerName $SERVER_NAME
APACHECONF
    a2enconf servername >/dev/null 2>&1 || true

    log_info "Memvalidasi konfigurasi Apache2..."
    if ! apache2ctl configtest; then
        log_error "Konfigurasi Apache2 tidak valid. Periksa output configtest di atas."
        return 1
    fi

    log_info "Menjalankan dan mengaktifkan service Apache2..."
    if ! systemctl enable apache2; then
        log_error "Gagal mengaktifkan service Apache2."
        return 1
    fi
    PORT_80_LISTENER="$(get_port_80_listener)"
    if [[ -n "$PORT_80_LISTENER" && "$PORT_80_LISTENER" != *"apache2"* ]]; then
        log_error "Port 80 sudah dipakai proses lain: $PORT_80_LISTENER"
        if [[ "$PORT_80_LISTENER" == *"docker-proxy"* ]]; then
            log_warn "Terdeteksi Docker memakai port 80. Stop container yang publish port 80 atau pindahkan Apache ke port lain."
        fi
        return 1
    fi
    if ! systemctl restart apache2; then
        log_error "Apache2 gagal dijalankan. Coba cek: systemctl status apache2 --no-pager && journalctl -xeu apache2.service"
        systemctl status apache2 --no-pager || true
        return 1
    fi

    log_info "Mengkonfigurasi firewall untuk port 80..."
    if command -v ufw &> /dev/null; then
        ufw allow 80/tcp
        log_info "UFW: Port 80 dibuka."
    fi

    log_info "Status Apache2:"
    systemctl status apache2 --no-pager | head -5
    log_info "✅ Apache2 berhasil diinstall! Akses: http://$(hostname -I | awk '{print $1}')"
}

# ─── vsftpd Installation ─────────────────────────────────────
install_ftp() {
    log_section "Instalasi FTP Server (vsftpd)"

    log_info "Menginstall vsftpd..."
    apt install -y vsftpd

    log_info "Membuat backup konfigurasi vsftpd..."
    cp /etc/vsftpd.conf /etc/vsftpd.conf.bak

    log_info "Mengkonfigurasi vsftpd..."
    cat > /etc/vsftpd.conf << 'FTPEOF'
# ── vsftpd Configuration - TechCorp ──
listen=YES
listen_ipv6=NO
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES
chroot_local_user=YES
allow_writeable_chroot=YES
secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=vsftpd
rsa_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
rsa_private_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
ssl_enable=NO
userlist_enable=YES
userlist_file=/etc/vsftpd.userlist
userlist_deny=NO
ftpd_banner=Welcome to TechCorp FTP Server
FTPEOF

    log_info "Membuat user FTP: admin..."
    if id "admin" &>/dev/null; then
        log_warn "User 'admin' sudah ada, melewati pembuatan user."
    else
        useradd -m -s /bin/bash admin
        echo "admin:123" | chpasswd
        log_info "User 'admin' berhasil dibuat dengan password: 123"
    fi

    log_info "Menambahkan user admin ke vsftpd userlist..."
    echo "admin" > /etc/vsftpd.userlist

    log_info "Membuat direktori FTP untuk user admin..."
    mkdir -p /home/admin/ftp/upload
    chown nobody:nogroup /home/admin/ftp
    chmod a-w /home/admin/ftp
    chown admin:admin /home/admin/ftp/upload
    chmod 755 /home/admin/ftp/upload

    log_info "Menjalankan dan mengaktifkan service vsftpd..."
    systemctl restart vsftpd
    systemctl enable vsftpd

    log_info "Mengkonfigurasi firewall untuk FTP..."
    if command -v ufw &> /dev/null; then
        ufw allow 20/tcp
        ufw allow 21/tcp
        log_info "UFW: Port 20 & 21 dibuka."
    fi

    log_info "Status vsftpd:"
    systemctl status vsftpd --no-pager | head -5
    log_info "✅ vsftpd berhasil diinstall! User: admin | Password: 123"
}

# ─── OpenSSH Installation ────────────────────────────────────
install_ssh() {
    log_section "Instalasi SSH Server (OpenSSH)"

    log_info "Menginstall openssh-server..."
    apt install -y openssh-server

    log_info "Membuat backup konfigurasi SSH..."
    cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak

    log_info "Mengkonfigurasi SSH (key-based auth, disable root login)..."
    sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
    sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
    sed -i 's/^#\?PubkeyAuthentication.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config
    sed -i 's/^#\?AuthorizedKeysFile.*/AuthorizedKeysFile .ssh\/authorized_keys/' /etc/ssh/sshd_config
    sed -i 's/^#\?ChallengeResponseAuthentication.*/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config

    log_info "Memastikan user admin ada..."
    if ! id "admin" &>/dev/null; then
        useradd -m -s /bin/bash admin
        echo "admin:123" | chpasswd
        log_info "User 'admin' dibuat."
    fi

    log_info "Membuat direktori .ssh untuk user admin..."
    mkdir -p /home/admin/.ssh
    chmod 700 /home/admin/.ssh

    log_info "Menambahkan contoh public key ke authorized_keys..."
    cat > /home/admin/.ssh/authorized_keys << 'KEYEOF'
# ── TechCorp SSH Authorized Keys ──
# Format: ssh-rsa/ssh-ed25519 <KEY> <COMMENT>
# Ganti baris di bawah dengan public key Anda yang sebenarnya
# Contoh:
# ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIExamplePublicKeyReplaceWithYourActualKey admin@techcorp
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC0ExampleKeyPlaceholder+TechCorpAdmin/ReplaceThisWithYourActualPublicKey== admin@techcorp-placeholder
KEYEOF

    chown -R admin:admin /home/admin/.ssh
    chmod 600 /home/admin/.ssh/authorized_keys

    log_info "Menjalankan dan mengaktifkan service SSH..."
    systemctl restart ssh
    systemctl enable ssh

    log_info "Mengkonfigurasi firewall untuk SSH..."
    if command -v ufw &> /dev/null; then
        ufw allow 22/tcp
        log_info "UFW: Port 22 dibuka."
    fi

    log_warn "PENTING: Ganti placeholder public key di /home/admin/.ssh/authorized_keys"
    log_warn "         dengan public key Anda yang sebenarnya sebelum login!"
    log_info "Status SSH:"
    systemctl status ssh --no-pager | head -5
    log_info "✅ OpenSSH berhasil dikonfigurasi! Key-based auth aktif, root login dinonaktifkan."
}

# ─── WordPress Installation ──────────────────────────────────
install_wordpress() {
    log_section "Instalasi WordPress (Optional)"

    log_info "Menginstall dependensi WordPress (PHP, MySQL client)..."
    apt install -y php php-mysql php-curl php-gd php-mbstring php-xml php-xmlrpc \
                   php-soap php-intl php-zip libapache2-mod-php wget unzip

    log_info "Menginstall MariaDB Server..."
    apt install -y mariadb-server mariadb-client
    systemctl start mariadb
    systemctl enable mariadb

    log_info "Membuat database dan user WordPress..."
    mysql -u root << 'SQLEOF'
CREATE DATABASE IF NOT EXISTS wordpress_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'wp_user'@'localhost' IDENTIFIED BY 'WpTechCorp@2024';
GRANT ALL PRIVILEGES ON wordpress_db.* TO 'wp_user'@'localhost';
FLUSH PRIVILEGES;
SQLEOF
    log_info "Database 'wordpress_db' dan user 'wp_user' berhasil dibuat."

    log_info "Mendownload WordPress versi terbaru..."
    # Gunakan subshell untuk isolasi
    (
        cd /tmp || { log_error "Gagal pindah ke /tmp"; return 1; }
        wget -q https://wordpress.org/latest.tar.gz -O wordpress.tar.gz
        log_info "Mengekstrak WordPress..."
        tar -xzf wordpress.tar.gz
        log_info "Memindahkan WordPress ke /var/www/html/wordpress..."
        mv wordpress /var/www/html/wordpress
        rm -f wordpress.tar.gz
    )

    log_info "Mengkonfigurasi wp-config.php..."
    cp /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php
    sed -i "s/database_name_here/wordpress_db/" /var/www/html/wordpress/wp-config.php
    sed -i "s/username_here/wp_user/" /var/www/html/wordpress/wp-config.php
    sed -i "s/password_here/WpTechCorp@2024/" /var/www/html/wordpress/wp-config.php

    log_info "Mengatur permission WordPress..."
    chown -R www-data:www-data /var/www/html/wordpress
    find /var/www/html/wordpress -type d -exec chmod 755 {} \;
    find /var/www/html/wordpress -type f -exec chmod 644 {} \;

    log_info "Mengaktifkan mod_rewrite untuk Apache..."
    a2enmod rewrite

    log_info "Membuat konfigurasi Virtual Host WordPress..."
    cat > /etc/apache2/sites-available/wordpress.conf << 'APACHEEOF'
<VirtualHost *:80>
    ServerAdmin webmaster@techcorp.id
    DocumentRoot /var/www/html/wordpress
    ServerName wordpress.techcorp.local

    <Directory /var/www/html/wordpress>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/wordpress_error.log
    CustomLog ${APACHE_LOG_DIR}/wordpress_access.log combined
</VirtualHost>
APACHEEOF

    a2ensite wordpress.conf
    systemctl restart apache2

    log_info "Membersihkan file temporary..."
    rm -f /tmp/wordpress.tar.gz

    log_info "✅ WordPress berhasil diinstall!"
    log_info "   URL: http://$(hostname -I | awk '{print $1}')/wordpress"
    log_info "   DB Name: wordpress_db | DB User: wp_user | DB Pass: WpTechCorp@2024"
    log_warn "   Segera ubah password database di wp-config.php untuk keamanan!"
}

# ─── Install All Services ────────────────────────────────────
install_all() {
    log_section "Instalasi Semua Service"
    log_info "Memulai instalasi lengkap: Apache2 + vsftpd + OpenSSH + WordPress..."
    system_update
    install_apache
    install_ftp
    install_ssh
    install_wordpress
    log_section "Instalasi Selesai"
    log_info "✅ Semua service berhasil diinstall!"
    echo ""
    echo -e "${GREEN}${BOLD}  ┌─────────────────────────────────────────────────┐${NC}"
    echo -e "${GREEN}${BOLD}  │           RINGKASAN INSTALASI                   │${NC}"
    echo -e "${GREEN}${BOLD}  ├─────────────────────────────────────────────────┤${NC}"
    echo -e "${GREEN}${BOLD}  │${NC}  🌐 Apache2  : http://$(hostname -I | awk '{print $1}')           ${GREEN}${BOLD}│${NC}"
    echo -e "${GREEN}${BOLD}  │${NC}  📁 FTP      : ftp://$(hostname -I | awk '{print $1}') (admin/123)${GREEN}${BOLD}│${NC}"
    echo -e "${GREEN}${BOLD}  │${NC}  🔒 SSH      : ssh admin@$(hostname -I | awk '{print $1}')        ${GREEN}${BOLD}│${NC}"
    echo -e "${GREEN}${BOLD}  │${NC}  📝 WordPress: http://$(hostname -I | awk '{print $1}')/wordpress ${GREEN}${BOLD}│${NC}"
    echo -e "${GREEN}${BOLD}  └─────────────────────────────────────────────────┘${NC}"
}

# ─── Main Program ────────────────────────────────────────────
main() {
    check_root
    show_banner

    while true; do
        show_menu
        prompt_menu_choice || exit 1
        case $CHOICE in
            1)
                install_all
                ;;
            2)
                system_update
                install_apache
                ;;
            3)
                system_update
                install_ftp
                ;;
            4)
                system_update
                install_ssh
                ;;
            5)
                system_update
                install_wordpress
                ;;
            6)
                echo -e "\n${CYAN}${BOLD}Terima kasih telah menggunakan TechCorp Installer. Sampai jumpa!${NC}\n"
                tput sgr0
                exit 0
                ;;
        esac

        echo ""
        read -r -p "$(echo -e "${YELLOW}Tekan Enter untuk kembali ke menu...${NC}")" < /dev/tty
        clear
        show_banner
    done
}

# ─── Entry Point ─────────────────────────────────────────────
main "$@"
